Feature/json to csv
BloomTech-Labs/human-rights-first-police-be-a pull request #4
Opened 2020-12-23 21:03 UTC by MarkRivera

# Description
Fixes # (issue)

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status
- [ ] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?
- [ ] Test A
- [ ] Test B

# Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

2020-12-28 23:42 UTC, jstewart8053 approved these changes, later dismissed

2020-12-28 23:43 UTC, jstewart8053 commented
Looks good! You may want to clean up some of the unused variables so the checks pass.

2020-12-29 03:34 UTC, mrockingham approved these changes, later dismissed
Looks good!

2021-01-03 23:48 UTC, jlong5795 requested changes
This endpoint will allow a download of the entire database as a CSV which is great! Once we know this works we can do the same with a queried endpoint and allow a CSV download of a specific variety.

2021-01-03 23:48 UTC, jlong5795 commented on api/incidents/incidentsRouter.js
> +    const fields = [
This file is a bit long already. Let's try taking this array and putting it into a resource/utility type file and them importing it here instead.

2021-01-04 08:27 UTC, jlong5795 approved these changes
Thank you for that revision. This will help keep this code maintainable.

2021-01-04 08:28 UTC, merged