Feature/incident tests
BloomTech-Labs/human-rights-first-police-be-a pull request #64
Opened 2021-08-11 02:32 UTC by joseph-witzke

# Description
Made edits to the "getIncidentById" model function test. Tests pass, but needs further review. 

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [√] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status
- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [√ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?
- [ ] Test A
- [ ] Test B

# Checklist
- [√ ] My code follows the style guidelines of this project
- [√ ] I have performed a self-review of my own code
- [√ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [√ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [√] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

<img width="567" alt="Screen Shot 2021-08-10 at 8 11 35 PM" src="https://user-images.githubusercontent.com/74194503/128960398-93ab408a-5b11-4ed5-9bfa-37d30cd86cd6.png">

2021-08-11 17:56 UTC, dylan-rinella commented
Looks great overall, this helped me get unstuck on a couple of unit tests that Ive bee working on.

2021-08-12 00:07 UTC, devbrunopaula approved these changes
Code looks clean, and its following industry standards.

2021-08-12 00:07 UTC, devbrunopaula commented on data/seeds/001-incidents.js
> +  return knex('force_ranks')
Great catch here. There isn't any incidents table.

2021-08-13 01:04 UTC, RyderBlues approved these changes
Good to go!

2021-08-13 01:17 UTC, RyderBlues requested changes
Package-lock merge issues

2021-08-16 18:35 UTC, closed without merging